use serde::{Deserialize, Serialize};

/// A step in a task plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcedureStep {
    pub step_number: u32,
    pub description: String,
    pub tool_name: String,
    pub tool_args: serde_json::Value,
    pub verification: Option<String>,
    pub on_failure: StepFailureAction,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StepFailureAction {
    Abort,
    Skip,
    Retry,
    Escalate,
}

/// A complete task plan generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskPlan {
    pub task_description: String,
    pub steps: Vec<ProcedureStep>,
    pub preconditions: Vec<String>,
    pub estimated_duration_s: u32,
}

/// A learned, reusable procedure template.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcedureTemplate {
    pub id: String,
    pub name: String,
    pub app_name: String,
    pub description: String,
    pub steps: Vec<ProcedureStep>,
    pub preconditions: Vec<String>,
    pub success_count: u32,
    pub failure_count: u32,
    pub last_used: u64,
    pub created_at: u64,
}

/// Result of a mimicry execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MimicryResult {
    pub task_description: String,
    pub success: bool,
    pub steps_completed: u32,
    pub steps_total: u32,
    pub error: Option<String>,
    pub procedure_id: Option<String>,
    pub duration_ms: u64,
}

/// AX tree snapshot captured before a step for undo diagnostics.
/// Held in memory only for the duration of a run; never persisted.
#[derive(Debug, Clone)]
pub struct UndoSnapshot {
    pub step: u32,
    pub ax_tree: serde_json::Value,
}

/// Progress event streamed during execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum MimicryProgress {
    PlanReady {
        plan: TaskPlan,
    },
    StepStarted {
        step: u32,
        description: String,
    },
    StepCompleted {
        step: u32,
        result: serde_json::Value,
    },
    StepFailed {
        step: u32,
        error: String,
    },
    StepBlocked {
        step: u32,
        reason: String,
    },
    Replanning {
        reason: String,
    },
    Done {
        result: MimicryResult,
    },
    Error {
        message: String,
    },
}
