use serde::{Deserialize, Serialize};

/// A step in a task plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcedureStep {
    pub step_number: u32,
    pub description: String,
    pub tool_name: String,
    pub tool_args: serde_json::Value,
    pub verification: Option<String>,
    pub on_failure: StepFailureAction,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StepFailureAction {
    Abort,
    Skip,
    Retry,
    Escalate,
}

/// A complete task plan generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskPlan {
    pub task_description: String,
    pub steps: Vec<ProcedureStep>,
    pub preconditions: Vec<String>,
    pub estimated_duration_s: u32,
}

/// A learned, reusable procedure template.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcedureTemplate {
    pub id: String,
    pub name: String,
    pub app_name: String,
    pub description: String,
    pub steps: Vec<ProcedureStep>,
    pub preconditions: Vec<String>,
    pub success_count: u32,
    pub failure_count: u32,
    pub last_used: u64,
    pub created_at: u64,
}

/// Result of a mimicry execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MimicryResult {
    pub task_description: String,
    pub success: bool,
    pub steps_completed: u32,
    pub steps_total: u32,
    pub error: Option<String>,
    pub procedure_id: Option<String>,
    pub duration_ms: u64,
}

/// AX tree snapshot captured before a step for undo diagnostics.
/// Held in memory only for the duration of a run; never persisted.
#[derive(Debug, Clone)]
pub struct UndoSnapshot {
    pub step: u32,
    pub ax_tree: serde_json::Value,
}

/// Progress event streamed during execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum MimicryProgress {
    PlanReady {
        plan: TaskPlan,
    },
    StepStarted {
        step: u32,
        description: String,
    },
    StepCompleted {
        step: u32,
        result: serde_json::Value,
    },
    StepFailed {
        step: u32,
        error: String,
    },
    StepBlocked {
        step: u32,
        reason: String,
    },
    Replanning {
        reason: String,
    },
    Done {
        result: MimicryResult,
    },
    Error {
        message: String,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn step_failure_action_uses_snake_case() {
        assert_eq!(
            serde_json::to_value(StepFailureAction::Abort).unwrap(),
            json!("abort")
        );
        assert_eq!(
            serde_json::to_value(StepFailureAction::Escalate).unwrap(),
            json!("escalate")
        );
        let parsed: StepFailureAction = serde_json::from_value(json!("retry")).unwrap();
        assert!(matches!(parsed, StepFailureAction::Retry));
    }

    #[test]
    fn step_failure_action_rejects_unknown_variant() {
        let r: Result<StepFailureAction, _> = serde_json::from_value(json!("boom"));
        assert!(r.is_err());
    }

    #[test]
    fn mimicry_progress_is_internally_tagged_snake_case() {
        let v = serde_json::to_value(MimicryProgress::StepStarted {
            step: 3,
            description: "click".to_string(),
        })
        .unwrap();
        assert_eq!(v["type"], json!("step_started"));
        assert_eq!(v["step"], json!(3));
        assert_eq!(v["description"], json!("click"));
    }

    #[test]
    fn mimicry_progress_step_failed_tag() {
        let v = serde_json::to_value(MimicryProgress::StepFailed {
            step: 1,
            error: "nope".to_string(),
        })
        .unwrap();
        assert_eq!(v["type"], json!("step_failed"));
        assert_eq!(v["error"], json!("nope"));
    }

    #[test]
    fn mimicry_progress_round_trips() {
        let original = MimicryProgress::Replanning {
            reason: "step 2 blocked".to_string(),
        };
        let s = serde_json::to_string(&original).unwrap();
        let back: MimicryProgress = serde_json::from_str(&s).unwrap();
        match back {
            MimicryProgress::Replanning { reason } => assert_eq!(reason, "step 2 blocked"),
            other => panic!("wrong variant: {other:?}"),
        }
    }

    #[test]
    fn procedure_step_round_trips_with_nested_args() {
        let step = ProcedureStep {
            step_number: 2,
            description: "type text".to_string(),
            tool_name: "ax_type".to_string(),
            tool_args: json!({"text": "hi", "into": "field"}),
            verification: Some("value shows hi".to_string()),
            on_failure: StepFailureAction::Skip,
        };
        let s = serde_json::to_string(&step).unwrap();
        let back: ProcedureStep = serde_json::from_str(&s).unwrap();
        assert_eq!(back.step_number, 2);
        assert_eq!(back.tool_args["text"], json!("hi"));
        assert_eq!(back.verification.as_deref(), Some("value shows hi"));
        assert!(matches!(back.on_failure, StepFailureAction::Skip));
    }

    #[test]
    fn mimicry_result_serializes_optional_fields() {
        let r = MimicryResult {
            task_description: "t".to_string(),
            success: false,
            steps_completed: 1,
            steps_total: 3,
            error: Some("failed".to_string()),
            procedure_id: None,
            duration_ms: 42,
        };
        let v = serde_json::to_value(&r).unwrap();
        assert_eq!(v["success"], json!(false));
        assert_eq!(v["steps_total"], json!(3));
        assert_eq!(v["error"], json!("failed"));
        assert_eq!(v["procedure_id"], json!(null));
    }
}
